version: "3.2"

services:
    postgres:
        build: ./db
        container_name: postgres
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U root --db-name db" ]
            interval: 10s
            timeout: 5s
            retries: 5
        env_file:
            - .env
        expose:
            - 5431
        ports:
            - 5431:5431
        restart: always
    server:
        build: .
        container_name: translation-aggregator-server
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            -   type: bind
                source: ./src/main/resources/static
                target: /app/src/main/resources/static
                read_only: true
            -   type: bind
                source: ./keys
                target: /app/keys
                read_only: true
        expose:
            - 8080
        ports:
            - 8080:8080
        restart: always
    test-server:
        build: .
        container_name: translation-aggregator-server-test
        environment:
            PORT: 8082
            TEST_MODE: "true"
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            -   type: bind
                source: ./src/main/resources/static
                target: /app/src/main/resources/static
                read_only: true
            -   type: bind
                source: ./keys
                target: /app/keys
                read_only: true
        expose:
            - 8082
        ports:
            - 8082:8082
        restart: always
